# Generated by Django 5.1.1 on 2024-10-02 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(default='paciente', max_length=50)),
                ('cedula', models.CharField(max_length=10, unique=True)),
                ('nombres', models.CharField(max_length=50)),
                ('apellidos', models.CharField(max_length=50)),
                ('correo', models.EmailField(default='default@example.com', max_length=254)),
                ('usuario', models.CharField(max_length=16)),
                ('password', models.CharField(default='default_password', max_length=128)),
            ],
        ),
    ]
