# Generated by Django 5.1.1 on 2024-12-19 05:42

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('citas', '0003_calificacion_dias_especialidad_horas_persona_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estadisticas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('nombre_reporte', models.CharField(max_length=100)),
                ('total_pacientes', models.PositiveIntegerField(default=0)),
                ('total_citas', models.PositiveIntegerField(default=0)),
                ('citas_pendientes', models.PositiveIntegerField(default=0)),
                ('citas_finalizadas', models.PositiveIntegerField(default=0)),
                ('citas_canceladas', models.PositiveIntegerField(default=0)),
                ('total_diagnosticos', models.PositiveIntegerField(default=0)),
                ('promedio_calificacion', models.FloatField(default=0.0)),
            ],
        ),
        migrations.RemoveField(
            model_name='horario',
            name='dias',
        ),
        migrations.RemoveField(
            model_name='horario',
            name='horas',
        ),
        migrations.RemoveField(
            model_name='medicohorario',
            name='horario',
        ),
        migrations.RemoveField(
            model_name='medicohorario',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='secretaria',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='persona',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol_usuario',
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AlterModelManagers(
            name='usuario',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.RemoveField(
            model_name='calificacion',
            name='puntuacion',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='estado_cita',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre_usuario',
        ),
        migrations.AddField(
            model_name='calificacion',
            name='calificacion',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=3),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='cita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion', to='citas.cita'),
        ),
        migrations.AddField(
            model_name='calificacion',
            name='comentario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('Cancelada', 'Cancelada'), ('En Atención', 'En Atención'), ('Finalizada', 'Finalizada')], default='Pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cedula',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ciudad_residencia',
            field=models.CharField(default='Desconocida', max_length=50),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo_electronico',
            field=models.EmailField(default='desconocido@dominio.com', max_length=254),
        ),
        migrations.AddField(
            model_name='usuario',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='Desconocida', max_length=150),
        ),
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino'), ('Otro', 'Otro')], default='Masculino', max_length=10),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='Los grupos a los que pertenece este usuario.', related_name='usuario_groups', to='auth.group', verbose_name='grupos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='last name'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default='Default Name', max_length=100),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='default_password', max_length=128),
        ),
        migrations.AddField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Permisos específicos para este usuario.', related_name='usuario_user_permissions', to='auth.permission', verbose_name='permisos de usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='username',
            field=models.CharField(default='default_username', max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='calificacion',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='estado',
            field=models.CharField(choices=[('Activa', 'Activa'), ('Inactiva', 'Inactiva')], default='Activa', max_length=20),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='fecha_modificacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='especialidad',
            name='fecha_registro',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.RemoveField(
            model_name='medico',
            name='especialidad',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citas.usuario'),
        ),
        migrations.AlterField(
            model_name='secretaria',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='citas.usuario'),
        ),
        migrations.CreateModel(
            name='Agenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('medico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agenda', to='citas.medico')),
            ],
        ),
        migrations.CreateModel(
            name='Diagnostico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cita', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostico', to='citas.cita')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos_medico', to='citas.medico')),
            ],
        ),
        migrations.CreateModel(
            name='ExamenMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha_solicitud', models.DateField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='citas.cita')),
            ],
        ),
        migrations.CreateModel(
            name='HistorialClinico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('antecedentes', models.TextField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True, null=True)),
                ('enfermedades_cronicas', models.TextField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historia', to='citas.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='HorarioMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=10)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('estado', models.CharField(choices=[('Disponible', 'Disponible'), ('No Disponible', 'No Disponible')], default='Disponible', max_length=20)),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='citas.medico')),
            ],
        ),
        migrations.CreateModel(
            name='RecetaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamentos', models.TextField()),
                ('indicaciones', models.TextField(blank=True, null=True)),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='citas.cita')),
            ],
        ),
        migrations.DeleteModel(
            name='AtencionMedica',
        ),
        migrations.DeleteModel(
            name='Dias',
        ),
        migrations.DeleteModel(
            name='Horas',
        ),
        migrations.DeleteModel(
            name='Horario',
        ),
        migrations.DeleteModel(
            name='MedicoHorario',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
        migrations.DeleteModel(
            name='RolUsuario',
        ),
        migrations.AddField(
            model_name='medico',
            name='especialidad',
            field=models.ManyToManyField(related_name='medicos', to='citas.especialidad'),
        ),
    ]
