# Generated by Django 5.1.1 on 2025-01-19 22:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_remove_cita_citas_cita_fecha_c_c50e2e_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horariomedico',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='horariomedico',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='horariomedico',
            name='dia',
            field=models.CharField(choices=[('Lunes', 'Lunes'), ('Martes', 'Martes'), ('Miércoles', 'Miércoles'), ('Jueves', 'Jueves'), ('Viernes', 'Viernes')], max_length=9),
        ),
        migrations.AlterField(
            model_name='horariomedico',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
