# Generated by Django 5.1.1 on 2025-01-20 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_remove_horariomedico_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paciente',
            name='foto_perfil',
        ),
    ]
