# Generated by Django 5.1.1 on 2025-01-21 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_remove_paciente_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='horariomedico',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 1, 1)),
            preserve_default=False,
        ),
    ]
