# Generated by Django 5.1.1 on 2025-01-25 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_cita_actualizado_el_cita_creado_el_alter_cita_estado_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialclinico',
            name='alergias',
        ),
        migrations.RemoveField(
            model_name='historialclinico',
            name='antecedentes',
        ),
        migrations.RemoveField(
            model_name='historialclinico',
            name='enfermedades_cronicas',
        ),
        migrations.RemoveField(
            model_name='historialclinico',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='diagnosticos',
            field=models.ManyToManyField(blank=True, related_name='historiales', to='citas.diagnostico'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='examenes',
            field=models.ManyToManyField(blank=True, related_name='historiales', to='citas.examenmedico'),
        ),
        migrations.AddField(
            model_name='historialclinico',
            name='recetas',
            field=models.ManyToManyField(blank=True, related_name='historiales', to='citas.recetamedica'),
        ),
    ]
