# Generated by Django 5.1.1 on 2025-01-25 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_remove_historialclinico_alergias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='calificacion',
            field=models.CharField(choices=[('Excelente', 'Excelente'), ('Muy bueno', 'Muy bueno'), ('Bueno', 'Bueno'), ('Regular', 'Regular'), ('Malo', 'Malo'), ('Pésimo', 'Pésimo')], default='Bueno', max_length=20),
        ),
    ]
