# Generated by Django 5.1.1 on 2025-01-26 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_alter_calificacion_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estadisticas',
            name='calificaciones_por_medico',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='citas_por_ano',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='citas_por_dia',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='citas_por_mes',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='citas_por_semana',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='estadisticas',
            name='pacientes_atendidos_por_especialidad',
            field=models.JSONField(default=dict),
        ),
    ]
