# Generated by Django 5.1.1 on 2025-01-26 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_estadisticas_calificaciones_por_medico_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calificacion',
            name='calificacion',
            field=models.IntegerField(choices=[(5, 'Excelente'), (4, 'Muy bueno'), (3, 'Bueno'), (2, 'Regular'), (1, 'Malo'), (0, 'Pésimo')], default=3),
        ),
    ]
