# Generated by Django 5.1.1 on 2025-01-26 21:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0013_alter_estadisticas_nombre_reporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='actualizado_el',
        ),
        migrations.RemoveField(
            model_name='cita',
            name='creado_el',
        ),
        migrations.AddField(
            model_name='cita',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
